---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Katoteros:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: http://status.katoteros.org
        description: Uptime Kuma
        widget:
            type: uptimekuma
            url: https://status.katoteros.org
            slug: neverland
    - Unifi:
        icon: unifi.svg
        href: https://unifi.katoteros.org
        description: Unifi Network
